name: clang-format linter

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: SimonRit/ITKClangFormatLinterAction@a87b73743ee2f32d37ce628c87731a0373612fa6
      with:
        itk-branch: master
